---
title: "cwd.datacleaning.updated.Rmd"
author: "Kaija Gahm"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load functions and libraries
```{r}
source("ownfunctions.R")
source("libraries.R")
```

## Load data
```{r}
load("../data/outputs/fish_data_EF.Rda") 
  # Fish sampling data
sites_p4p8p13 <- read.csv("../data/inputs/DataSets_7_7/AttributeTables/sites_p4p8p13.txt") 
  # reprojected data
rivmi <- read.table("../data/inputs/p4p8p13_rivmile.txt", sep = ",", header = T) 
  # river mile data
sites_aa_5m <- read.csv("../data/inputs/DataSets_7_7/AttributeTables/sites_aquaareas5m.txt") 
  # merged aquatic areas data for points buffered by 5 meters.
sites_terrestrial <- read.csv("../data/inputs/DataSets_7_7/AttributeTables/sites_terrestrial.txt") 
  # nearest terrestrial area info for each point
terrestrial_forests <- read.csv("../data/inputs/DataSets_7_7/AttributeTables/Terrestrial_Forests.txt") 
  # info about terrestrial areas/forests
sites_forest <- read.csv("../data/inputs/DataSets_7_7/AttributeTables/sites_forest.txt") 
  # nearest forest info for each point
lc_2010 <- read.csv("../data/inputs/DataSets_7_7/AttributeTables/lc_2010.txt") 
  # 2010 landcover info
```

## Join river miles to sites_p4p8p13
```{r}
# To add river mile data, we have to go via sites_p4p8p13 because of the correspondence between object codes in GIS.

# Identify corresponding columns
sites_p4p8p13 %<>% rename(siteid = FID)
rivmi %<>% rename(siteid = TARGET_FID) 

# Select columns of river miles data frame to prepare for join
rivmi_reduced <- rivmi %>% select(siteid, RIVER_MILE)

# Perform join
sites <- left_join(sites_p4p8p13, rivmi_reduced, by = "siteid")
```

## Join river miles to sites_aa_5m
```{r}
# Join barcodes to sites_p4p8p13. This will allow for a join with sites_aa_5m.
sites %<>% rename(fishdata_rownum = Field1) # the Field1 column in this dataset corresponds to the row number in fish_data_EF.
rows <- sites$fishdata_rownum # get vector of fish data row numbers in the order they appear in the sites data.
sites$barcode <- fish_data_EF$barcode[rows] # add barcodes to sites data

### Join barcodes for sites_aa_5m
sites_aa_5m$barcode <- fish_data_EF$barcode[rows]

### use barcode matching to join river miles into sites_aa_5m. 
sites_aa_5m <- left_join(sites_aa_5m, sites[,c("barcode", "RIVER_MILE")], by = "barcode")
### Ok, now we're done with the sites data frame.
```

## Further cleaning of sites_aa_5m
```{r}
# add pool information
sites_aa_5m$pool <- fish_data_EF$pool[rows]

# "Observations with value of 0 in all the columns from aqa_2010_lvl3_011918.shp do not intersect with the aquatic areas layer". I'd like these to have values of NA, not 0. 
badrows_5 <- sites_aa_5m  %>% filter(Perimeter == 0, Area == 0, avg_fetch == 0)
dim(badrows_5)

# Remove the bad rows
sites_aa_5m <- sites_aa_5m %>% filter(Field1 %notin% badrows_5$Field1)
dim(sites_aa_5m)

# Check for missing values
locate.nas(sites_aa_5m)

# Fix missing pools
# there are a concerning number of NA's in the `pool` column that shouldn't be there. Luckily, the `uniq_id` column tells us which pool these are from. 
addpools <- function(df){
  pools <- as.numeric(substr(x = as.character(df$uniq_id), 
                             start = 2, 
                             stop = 3))
  df$pool[is.na(df$pool)] <- pools[is.na(df$pool)]
  return(df)
}
sites_aa_5m <- addpools(sites_aa_5m)
locate.nas(sites_aa_5m) # we still have some NA's for "snag", but that is to be expected. 
```

## Join environmental info
### Distance to terrestrial areas
```{r}
# terrestrial data to join
terr_tojoin <- sites_terrestrial %>% select(NEAR_FID, NEAR_DIST, Field1)
sites_aa_5m <- left_join(sites_aa_5m, terr_tojoin, by = "Field1") %>% 
  rename(NEAR_TERR_FID = NEAR_FID, # ID of nearest terrestrial region
         NEAR_TERR_DIST = NEAR_DIST) # distance to nearest terrestrial region

# The is the join that I think I was trying to do originally. It assumes that Field1 in sites_terrestrial is equivalent to Field1 in sites_aa_5m. Need to check that this is right.

# ID of nearest terrestrial region
```

### Info about nearest terrestrial region
```{r}
# We're going to pull terrestrial areas information columns from `lc_2010`, not from `terrestrial`, because the FID's don't match up in `terrestrial`.
terrinfo_tojoin <- lc_2010 %>% select(FID, CLASS_7_C, CLASS_7_N)
sites_aa_5m <- left_join(sites_aa_5m, terrinfo_tojoin, by = c("NEAR_TERR_FID" = "FID")) %>%
  rename(NEAR_TERR_CLASS_7 = CLASS_7_C,
         NEAR_TERR_CLASS_7_N = CLASS_7_N) # join the columns and rename appropriately
```

### Distance to forested areas
```{r}
forest_tojoin <- sites_forest %>% select(Field1, NEAR_FID, NEAR_DIST)
sites_aa_5m <- left_join(sites_aa_5m, forest_tojoin, by = "Field1") %>% 
  rename(NEAR_FOREST_FID = NEAR_FID, # which forested area is the closest
         NEAR_FOREST_DIST = NEAR_DIST) # distance to nearest forested area
```

