library(tidyverse)
library(wesanderson)
library(ggmap)
library(chron)
library(MASS)
library(plyr)
library(rgdal)
library(sp)
library(car)
library(RColorBrewer)
library(rgeos) 
library(scales)
library(cluster)
library(fpc)
library(maptools)
library(rfishbase)
library(nnet)
library(corrplot)
library(data.table)
library(broom)
library(vegan)
library(rpart)
library(rpart.plot)
library(xtable)
library(randomForest)
library(ggfortify)
library(boot)
library(TPD)
library(RADanalysis)
library(colorRamps)
library(ggpubr)
library(lubridate)
library(jtools)
library(party)
library(partykit)
library(pROC)
library(lme4)
library(effects)
library(stringr)
library(DescTools)
library(segmented) # for time series
library(cpm) # for time series
library(trend) # for time series

